version: '3.9'
services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 246808642aA@
      MYSQL_DATABASE: mailer
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    container_name: proto_sql
    networks:
      - api

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - '5001:5000'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 246808642aA@
      MYSQL_DATABASE: mailer
    container_name: proto_back
    command: >
      bash -c "./wait-for-it.sh db:3306 -- python app.py"
    depends_on:
      - db
    networks:
      - api

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/proto_app/dist
    container_name: proto_front_build
    depends_on:
      - backend
      - db
    networks:
      - api

  nginx:
    image: nginx:stable-alpine
    container_name: proto_nginx
    ports:
      - '80:80'
    volumes:
      - frontend_build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - api

networks:
  api:

volumes:
  mysql_data:
  frontend_build:
